repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01-MARLYN-WESCOFF
repo_name: 2025-1-T01-MARLYN-WESCOFF
site_name: Grupo Marlyn Wescoff - Turma 1 (2025.1)
site_url: 

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Light mode
      primary: indigo
      accent: indigo

markdown_extensions:
  - attr_list
  - tables

nav:
  - Início: index.md
  - GQM: GQM.md
              